// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/minskylab/meta-core/ent/credential"
	"github.com/minskylab/meta-core/ent/deployment"
	"github.com/minskylab/meta-core/ent/process"
	"github.com/minskylab/meta-core/ent/provider"
	"github.com/minskylab/meta-core/ent/schema"
	"github.com/minskylab/meta-core/ent/stack"
	"github.com/minskylab/meta-core/ent/task"
	uuid "github.com/satori/go.uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescCreatedAt is the schema descriptor for created_at field.
	credentialDescCreatedAt := credentialFields[1].Descriptor()
	// credential.DefaultCreatedAt holds the default value on creation for the created_at field.
	credential.DefaultCreatedAt = credentialDescCreatedAt.Default.(func() time.Time)
	// credentialDescUpdatedAt is the schema descriptor for updated_at field.
	credentialDescUpdatedAt := credentialFields[2].Descriptor()
	// credential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	credential.DefaultUpdatedAt = credentialDescUpdatedAt.Default.(func() time.Time)
	// credential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	credential.UpdateDefaultUpdatedAt = credentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	// credentialDescID is the schema descriptor for id field.
	credentialDescID := credentialFields[0].Descriptor()
	// credential.DefaultID holds the default value on creation for the id field.
	credential.DefaultID = credentialDescID.Default.(func() uuid.UUID)
	deploymentFields := schema.Deployment{}.Fields()
	_ = deploymentFields
	// deploymentDescCreatedAt is the schema descriptor for created_at field.
	deploymentDescCreatedAt := deploymentFields[1].Descriptor()
	// deployment.DefaultCreatedAt holds the default value on creation for the created_at field.
	deployment.DefaultCreatedAt = deploymentDescCreatedAt.Default.(func() time.Time)
	// deploymentDescUpdatedAt is the schema descriptor for updated_at field.
	deploymentDescUpdatedAt := deploymentFields[2].Descriptor()
	// deployment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deployment.DefaultUpdatedAt = deploymentDescUpdatedAt.Default.(func() time.Time)
	// deployment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deployment.UpdateDefaultUpdatedAt = deploymentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deploymentDescName is the schema descriptor for name field.
	deploymentDescName := deploymentFields[4].Descriptor()
	// deployment.DefaultName holds the default value on creation for the name field.
	deployment.DefaultName = deploymentDescName.Default.(string)
	// deploymentDescTimeout is the schema descriptor for timeout field.
	deploymentDescTimeout := deploymentFields[5].Descriptor()
	// deployment.TimeoutValidator is a validator for the "timeout" field. It is called by the builders before save.
	deployment.TimeoutValidator = deploymentDescTimeout.Validators[0].(func(int) error)
	// deploymentDescID is the schema descriptor for id field.
	deploymentDescID := deploymentFields[0].Descriptor()
	// deployment.DefaultID holds the default value on creation for the id field.
	deployment.DefaultID = deploymentDescID.Default.(func() uuid.UUID)
	processFields := schema.Process{}.Fields()
	_ = processFields
	// processDescCreatedAt is the schema descriptor for created_at field.
	processDescCreatedAt := processFields[1].Descriptor()
	// process.DefaultCreatedAt holds the default value on creation for the created_at field.
	process.DefaultCreatedAt = processDescCreatedAt.Default.(func() time.Time)
	// processDescUpdatedAt is the schema descriptor for updated_at field.
	processDescUpdatedAt := processFields[2].Descriptor()
	// process.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	process.DefaultUpdatedAt = processDescUpdatedAt.Default.(func() time.Time)
	// process.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	process.UpdateDefaultUpdatedAt = processDescUpdatedAt.UpdateDefault.(func() time.Time)
	// processDescTimeout is the schema descriptor for timeout field.
	processDescTimeout := processFields[8].Descriptor()
	// process.TimeoutValidator is a validator for the "timeout" field. It is called by the builders before save.
	process.TimeoutValidator = processDescTimeout.Validators[0].(func(int) error)
	// processDescExpiration is the schema descriptor for expiration field.
	processDescExpiration := processFields[9].Descriptor()
	// process.ExpirationValidator is a validator for the "expiration" field. It is called by the builders before save.
	process.ExpirationValidator = processDescExpiration.Validators[0].(func(int) error)
	providerFields := schema.Provider{}.Fields()
	_ = providerFields
	// providerDescCreatedAt is the schema descriptor for created_at field.
	providerDescCreatedAt := providerFields[1].Descriptor()
	// provider.DefaultCreatedAt holds the default value on creation for the created_at field.
	provider.DefaultCreatedAt = providerDescCreatedAt.Default.(func() time.Time)
	// providerDescUpdatedAt is the schema descriptor for updated_at field.
	providerDescUpdatedAt := providerFields[2].Descriptor()
	// provider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	provider.DefaultUpdatedAt = providerDescUpdatedAt.Default.(func() time.Time)
	// provider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	provider.UpdateDefaultUpdatedAt = providerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// providerDescID is the schema descriptor for id field.
	providerDescID := providerFields[0].Descriptor()
	// provider.DefaultID holds the default value on creation for the id field.
	provider.DefaultID = providerDescID.Default.(func() uuid.UUID)
	stackFields := schema.Stack{}.Fields()
	_ = stackFields
	// stackDescCreatedAt is the schema descriptor for created_at field.
	stackDescCreatedAt := stackFields[1].Descriptor()
	// stack.DefaultCreatedAt holds the default value on creation for the created_at field.
	stack.DefaultCreatedAt = stackDescCreatedAt.Default.(func() time.Time)
	// stackDescUpdatedAt is the schema descriptor for updated_at field.
	stackDescUpdatedAt := stackFields[2].Descriptor()
	// stack.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	stack.DefaultUpdatedAt = stackDescUpdatedAt.Default.(func() time.Time)
	// stack.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	stack.UpdateDefaultUpdatedAt = stackDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[1].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[2].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescDetached is the schema descriptor for detached field.
	taskDescDetached := taskFields[7].Descriptor()
	// task.DefaultDetached holds the default value on creation for the detached field.
	task.DefaultDetached = taskDescDetached.Default.(bool)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
}
