// Code generated by entc, DO NOT EDIT.

package process

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the process type in the database.
	Label = "process"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldInstanceType holds the string denoting the instance_type field in the database.
	FieldInstanceType = "instance_type"
	// FieldAmiID holds the string denoting the ami_id field in the database.
	FieldAmiID = "ami_id"
	// FieldResourcePrefix holds the string denoting the resource_prefix field in the database.
	FieldResourcePrefix = "resource_prefix"
	// FieldTimeout holds the string denoting the timeout field in the database.
	FieldTimeout = "timeout"
	// FieldExpiration holds the string denoting the expiration field in the database.
	FieldExpiration = "expiration"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// EdgeStack holds the string denoting the stack edge name in mutations.
	EdgeStack = "stack"
	// EdgeCredentials holds the string denoting the credentials edge name in mutations.
	EdgeCredentials = "credentials"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the process in the database.
	Table = "processes"
	// StackTable is the table that holds the stack relation/edge.
	StackTable = "processes"
	// StackInverseTable is the table name for the Stack entity.
	// It exists in this package in order to avoid circular dependency with the "stack" package.
	StackInverseTable = "stacks"
	// StackColumn is the table column denoting the stack relation/edge.
	StackColumn = "process_stack"
	// CredentialsTable is the table that holds the credentials relation/edge.
	CredentialsTable = "credentials"
	// CredentialsInverseTable is the table name for the Credential entity.
	// It exists in this package in order to avoid circular dependency with the "credential" package.
	CredentialsInverseTable = "credentials"
	// CredentialsColumn is the table column denoting the credentials relation/edge.
	CredentialsColumn = "process_credentials"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "tasks"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "process_tasks"
)

// Columns holds all SQL columns for process fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldToken,
	FieldInstanceType,
	FieldAmiID,
	FieldResourcePrefix,
	FieldTimeout,
	FieldExpiration,
	FieldState,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "processes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"process_stack",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TimeoutValidator is a validator for the "timeout" field. It is called by the builders before save.
	TimeoutValidator func(int) error
	// ExpirationValidator is a validator for the "expiration" field. It is called by the builders before save.
	ExpirationValidator func(int) error
)

// State defines the type for the "state" enum field.
type State string

// StatePENDING is the default value of the State enum.
const DefaultState = StatePENDING

// State values.
const (
	StatePENDING      State = "PENDING"
	StatePROVISIONING State = "PROVISIONING"
	StateDEPLOYING    State = "DEPLOYING"
	StateRUNNING      State = "RUNNING"
	StateIDLE         State = "IDLE"
	StateSTOPPING     State = "STOPPING"
	StateEXIT_TIMEOUT State = "EXIT_TIMEOUT"
	StateEXIT_SUCCESS State = "EXIT_SUCCESS"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePENDING, StatePROVISIONING, StateDEPLOYING, StateRUNNING, StateIDLE, StateSTOPPING, StateEXIT_TIMEOUT, StateEXIT_SUCCESS:
		return nil
	default:
		return fmt.Errorf("process: invalid enum value for state field: %q", s)
	}
}
