// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)

// Deployment is the predicate function for deployment builders.
type Deployment func(*sql.Selector)

// Process is the predicate function for process builders.
type Process func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// Stack is the predicate function for stack builders.
type Stack func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
